import React, { useState, useEffect, useRef } from 'react';
import { n, fmtNum, goNext } from '../utils/constants';
type Dia = 8 | 10 | 12 | 14 | 16 | 18 | 20;
interface MiddaModel {
  id: number;
    buildingLength: string; buildingWidth: string; lengthAxes: string; widthAxes: string;
      middaHeight: string; beamWidth: string; topCount: string; topDia: Dia;
        bottomCount: string; bottomDia: Dia; stirrupsPM: string; stirrupDia: Dia;
        }
        const dias: Dia[] = [8,10,12,14,16,18,20];
        const STORAGE_KEY = 'middat';
        const toTons = (bars: number, d: Dia) => bars / ({8:200,10:135,12:90,14:68,16:52,18:41,20:33}[d]||100);

        const SectionTitle = ({ children }: { children: React.ReactNode }) => (
          <div style={{ position:'relative', padding:'8px 12px', marginBottom:'12px', marginTop:'8px', background:'linear-gradient(to left, transparent, #e8f0fe 30%)', borderRight:'4px solid #2563eb', borderRadius:'0 8px 8px 0', boxShadow:'0 0 8px rgba(37,99,235,0.1)' }}>
              <span style={{ fontSize:'0.8rem', fontWeight:800, color:'#003366' }}>{children}</span>
                </div>
                );

                const Num = ({ id, go, label, value, set, unit }: any) => {
                  const inputRef = useRef<HTMLInputElement>(null);
                    const save = () => { if (inputRef.current) set(inputRef.current.value); };        
                      return (
                          <div style={{ background:'#fdfdfd', border:'1px solid #ddd', borderRadius:'8px', padding:'8px 5px', textAlign:'center' }}>
                                <label style={{ fontSize:'0.6rem', color:'#003366', display:'block', marginBottom:'2px', fontWeight:700 }}>{label}</label>
                                      <input id={id} type="text" inputMode="decimal" autoComplete="off" enterKeyHint={go?'next':'done'} ref={inputRef} defaultValue={value} onBlur={save} onFocus={e => e.target.select()} onKeyDown={e => { if (e.key==='Enter') { e.preventDefault(); save(); goNext(go); } }} style={{ width:'100%', border:'none', textAlign:'center', fontSize:'0.85rem', padding:'2px 0', outline:'none', background:'transparent', fontWeight:700, fontFamily:'Cairo, sans-serif' }} />
                                            {unit && <span style={{ fontSize:'0.55rem', color:'#888', display:'block', marginTop:'2px' }}>{unit}</span>}
                                                </div>
                                                  );
                                                  };

                                                  const Middat: React.FC = () => {
                                                    const [models, setModels] = useState<MiddaModel[]>(() => {
                                                        try { const s = localStorage.getItem(STORAGE_KEY); return s ? JSON.parse(s) : [{ id:1, buildingLength:'10', buildingWidth:'10', lengthAxes:'2', widthAxes:'2', middaHeight:'40', beamWidth:'20', topCount:'4', topDia:16, bottomCount:'4', bottomDia:16, stirrupsPM:'5', stirrupDia:8 }]; }
                                                            catch { return [{ id:1, buildingLength:'10', buildingWidth:'10', lengthAxes:'2', widthAxes:'2', middaHeight:'40', beamWidth:'20', topCount:'4', topDia:16, bottomCount:'4', bottomDia:16, stirrupsPM:'5', stirrupDia:8 }]; }
                                                              });
                                                                const [openModel, setOpenModel] = useState<number>(1);

                                                                  useEffect(() => { localStorage.setItem(STORAGE_KEY, JSON.stringify(models)); }, [models]);

                                                                    const addModel = () => { const id = Date.now(); setModels(prev => [...prev, { id, buildingLength:'10', buildingWidth:'10', lengthAxes:'2', widthAxes:'2', middaHeight:'40', beamWidth:'20', topCount:'4', topDia:16, bottomCount:'4', bottomDia:16, stirrupsPM:'5', stirrupDia:8 }]); setOpenModel(id); };
                                                                      const updateModel = (id: number, data: Partial<MiddaModel>) => { setModels(prev => prev.map(m => m.id===id ? {...m, ...data} : m)); };
                                                                        const deleteModel = (id: number) => { if (models.length>1) { setModels(prev => prev.filter(m => m.id!==id)); if (openModel===id) setOpenModel(models[0].id); } };

                                                                          const allSteel: any[] = [];
                                                                            let totalConcrete = 0;
                                                                              models.forEach((m, idx) => {
                                                                                  const bl = n(m.buildingLength), bw = n(m.buildingWidth);
                                                                                      const tl = bl*n(m.lengthAxes) + bw*n(m.widthAxes);
                                                                                          const h = n(m.middaHeight)/100, bwm = n(m.beamWidth)/100;
                                                                                              totalConcrete += Math.ceil(tl*bwm*h*100)/100;
                                                                                                  const tb = Math.ceil((n(m.topCount)*tl*1.1)/12), bb = Math.ceil((n(m.bottomCount)*tl*1.1)/12);
                                                                                                      const sb = Math.ceil((tl*n(m.stirrupsPM)*(2*(bwm+h)+0.2))/12);
                                                                                                          allSteel.push({ label:`ميدة ${idx+1} - علوي`, diameter:m.topDia, bars:tb, ton:toTons(tb,m.topDia) });
                                                                                                              allSteel.push({ label:`ميدة ${idx+1} - سفلي`, diameter:m.bottomDia, bars:bb, ton:toTons(bb,m.bottomDia) });
                                                                                                                  allSteel.push({ label:`ميدة ${idx+1} - كانات`, diameter:m.stirrupDia, bars:sb, ton:toTons(sb,m.stirrupDia) });
                                                                                                                    });
const totalSteelTon = allSteel.reduce((s: number, r: any) => s+r.ton, 0);

const calculate = () => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(models));
      
        const summaryByDia: Record<number, number> = {};
          allSteel.forEach(item => { summaryByDia[item.diameter] = (summaryByDia[item.diameter] || 0) + item.bars; });
            localStorage.setItem('middat_results', JSON.stringify({
                concrete: totalConcrete,
                    steel: summaryByDia,
                        totalSteelTons: totalSteelTon
                          }));
                          };


                              return (
                                                                                                                  
                                                                                                                            <div style={{ display:'flex', flexDirection:'column', gap:'12px' }}>
                                                                                                                                  <button onClick={addModel} className="no-print" style={{ width:'100%', padding:'12px', border:'2px dashed #00509e', borderRadius:'12px', background:'#e8f0fe', color:'#00509e', fontWeight:700, fontSize:'0.85rem', cursor:'pointer', fontFamily:'Cairo, sans-serif' }}>+ إضافة نموذج ميدة</button>
                                                                                                                                        {models.map((m, idx) => (
                                                                                                                                                <div key={m.id}>
                                                                                                                                                          <div onClick={() => setOpenModel(openModel===m.id?0:m.id)} style={{ display:'flex', justifyContent:'space-between', alignItems:'center', padding:'10px 12px', background:'#f8fafc', cursor:'pointer', border:'1px solid #ddd', borderRadius:'12px' }}>
                                                                                                                                                                      <span style={{ fontWeight:700, color:'#003366', fontSize:'0.9rem' }}>ميدة {idx+1}</span>
                                                                                                                                                                                  <div style={{ display:'flex', gap:'8px', alignItems:'center' }}>
                                                                                                                                                                                                {models.length>1 && <button onClick={e => { e.stopPropagation(); deleteModel(m.id); }} style={{ background:'#dc3545', color:'white', border:'none', borderRadius:'6px', padding:'4px 10px', fontSize:'0.7rem', cursor:'pointer', fontWeight:700 }}>🗑️</button>}
                                                                                                                                                                                                              <span>{openModel===m.id?'▲':'▼'}</span>
                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                              {openModel===m.id && (
                                                                                                                                                                                                                                                          <div style={{ border:'1px solid #ddd', borderRadius:'12px', overflow:'hidden', background:'white', marginBottom:'8px', padding:'10px 12px' }}>
                                                                                                                                                                                                                                                                        <SectionTitle>الأبعاد</SectionTitle>
                                                                                                                                                                                                                                                                                      <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:'8px', marginBottom:'12px' }}>
                                                                                                                                                                                                                                                                                                      <Num id={`bl-${m.id}`} label="طول المبنى" value={m.buildingLength} set={(v:string)=>updateModel(m.id,{buildingLength:v})} unit="م" />
                                                                                                                                                                                                                                                                                                                      <Num id={`bw-${m.id}`} label="عرض المبنى" value={m.buildingWidth} set={(v:string)=>updateModel(m.id,{buildingWidth:v})} unit="م" />
                                                                                                                                                                                                                                                                                                                                      <Num id={`la-${m.id}`} label="محاور الطول" value={m.lengthAxes} set={(v:string)=>updateModel(m.id,{lengthAxes:v})} unit="محور" />
                                                                                                                                                                                                                                                                                                                                                      <Num id={`wa-${m.id}`} label="محاور العرض" value={m.widthAxes} set={(v:string)=>updateModel(m.id,{widthAxes:v})} unit="محور" />
                                                                                                                                                                                                                                                                                                                                                                      <Num id={`h-${m.id}`} label="ارتفاع الميدة" value={m.middaHeight} set={(v:string)=>updateModel(m.id,{middaHeight:v})} unit="سم" />
                                                                                                                                                                                                                                                                                                                                                                                      <Num id={`bw2-${m.id}`} label="عرض الميدة" value={m.beamWidth} set={(v:string)=>updateModel(m.id,{beamWidth:v})} unit="سم" />
                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                  <SectionTitle>التسليح العلوي</SectionTitle>
                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ display:'flex', gap:'8px', marginBottom:'12px', border:'1px solid #ddd', borderRadius:'8px', padding:'8px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ flex:1 }}><label style={{ fontSize:'0.6rem', color:'#003366', display:'block', marginBottom:'2px', fontWeight:700, textAlign:'center' }}>عدد الأسياخ</label><input id={`top-${m.id}`} type="text" inputMode="decimal" autoComplete="off" defaultValue={m.topCount} onBlur={e=>updateModel(m.id,{topCount:e.target.value})} onFocus={e=>e.target.select()} style={{ width:'100%', border:'1px solid #ccc', borderRadius:'5px', padding:'4px', fontSize:'0.85rem', textAlign:'center', fontFamily:'Cairo, sans-serif', fontWeight:700 }} /></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ width:'80px' }}><label style={{ fontSize:'0.6rem', color:'#003366', display:'block', marginBottom:'2px', fontWeight:700, textAlign:'center' }}>القطر</label><select id={`topd-${m.id}`} value={m.topDia} onChange={e=>updateModel(m.id,{topDia:Number(e.target.value) as Dia})} style={{ width:'100%', border:'1px solid #ccc', borderRadius:'5px', padding:'4px', fontSize:'0.85rem', textAlign:'center', fontFamily:'Cairo, sans-serif', background:'white', fontWeight:700 }}>{dias.map(d=><option key={d} value={d}>{d} مم</option>)}</select></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <SectionTitle>التسليح السفلي</SectionTitle>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ display:'flex', gap:'8px', marginBottom:'12px', border:'1px solid #ddd', borderRadius:'8px', padding:'8px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ flex:1 }}><label style={{ fontSize:'0.6rem', color:'#003366', display:'block', marginBottom:'2px', fontWeight:700, textAlign:'center' }}>عدد الأسياخ</label><input id={`bot-${m.id}`} type="text" inputMode="decimal" autoComplete="off" defaultValue={m.bottomCount} onBlur={e=>updateModel(m.id,{bottomCount:e.target.value})} onFocus={e=>e.target.select()} style={{ width:'100%', border:'1px solid #ccc', borderRadius:'5px', padding:'4px', fontSize:'0.85rem', textAlign:'center', fontFamily:'Cairo, sans-serif', fontWeight:700 }} /></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ width:'80px' }}><label style={{ fontSize:'0.6rem', color:'#003366', display:'block', marginBottom:'2px', fontWeight:700, textAlign:'center' }}>القطر</label><select id={`botd-${m.id}`} value={m.bottomDia} onChange={e=>updateModel(m.id,{bottomDia:Number(e.target.value) as Dia})} style={{ width:'100%', border:'1px solid #ccc', borderRadius:'5px', padding:'4px', fontSize:'0.85rem', textAlign:'center', fontFamily:'Cairo, sans-serif', background:'white', fontWeight:700 }}>{dias.map(d=><option key={d} value={d}>{d} مم</option>)}</select></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <SectionTitle>الكانات / م</SectionTitle>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ display:'flex', gap:'8px', marginBottom:'12px', border:'1px solid #ddd', borderRadius:'8px', padding:'8px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ flex:1 }}><label style={{ fontSize:'0.6rem', color:'#003366', display:'block', marginBottom:'2px', fontWeight:700, textAlign:'center' }}>عدد الكانات</label><input id={`st-${m.id}`} type="text" inputMode="decimal" autoComplete="off" defaultValue={m.stirrupsPM} onBlur={e=>updateModel(m.id,{stirrupsPM:e.target.value})} onFocus={e=>e.target.select()} style={{ width:'100%', border:'1px solid #ccc', borderRadius:'5px', padding:'4px', fontSize:'0.85rem', textAlign:'center', fontFamily:'Cairo, sans-serif', fontWeight:700 }} /></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ width:'80px' }}><label style={{ fontSize:'0.6rem', color:'#003366', display:'block', marginBottom:'2px', fontWeight:700, textAlign:'center' }}>القطر</label><select id={`std-${m.id}`} value={m.stirrupDia} onChange={e=>updateModel(m.id,{stirrupDia:Number(e.target.value) as Dia})} style={{ width:'100%', border:'1px solid #ccc', borderRadius:'5px', padding:'4px', fontSize:'0.85rem', textAlign:'center', fontFamily:'Cairo, sans-serif', background:'white', fontWeight:700 }}>{dias.map(d=><option key={d} value={d}>{d} مم</option>)}</select></div>
                                                                                      </div>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
))}

<button onClick={calculate} className="no-print" style={{ width: '100%', padding: '12px', border: 'none', borderRadius: '10px', background: '#00509e', color: 'white', fontWeight: 700, fontSize: '0.85rem', cursor: 'pointer', fontFamily: 'Cairo, sans-serif', marginBottom: '12px' }}>🧮 حساب الكميات</button>

<div style={{ pageBreakBefore:'always' }}>
  <SectionTitle>النتائج</SectionTitle>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:'8px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ border:'1px solid #28a745', borderRadius:'10px', padding:'10px 8px', textAlign:'center', background:'#fafffe' }}><span style={{ fontSize:'0.55rem', color:'#555', fontWeight:700 }}>إجمالي الخرسانة</span><strong style={{ fontSize:'1rem', fontWeight:700, color:'#28a745', display:'block' }}>{fmtNum(totalConcrete)} م³</strong></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ border:'1px solid #28a745', borderRadius:'10px', padding:'10px 8px', textAlign:'center', background:'#fafffe' }}><span style={{ fontSize:'0.55rem', color:'#555', fontWeight:700 }}>إجمالي الحديد</span><strong style={{ fontSize:'1rem', fontWeight:700, color:'#28a745', display:'block' }}>{fmtNum(totalSteelTon)} طن</strong></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                  <SectionTitle>جدول الحديد</SectionTitle>
                                                                                  <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.7rem' }}>
                                                                                    <thead>
                                                                                        <tr style={{ background: '#003366', color: 'white' }}>
                                                                                              <th style={{ padding: '8px 5px', border: '1px solid #003366' }}>البند</th>
                                                                                                    <th style={{ padding: '8px 5px', border: '1px solid #003366' }}>القطر</th>
                                                                                                          <th style={{ padding: '8px 5px', border: '1px solid #003366' }}>عدد الأسياخ</th>
                                                                                                                <th style={{ padding: '8px 5px', border: '1px solid #003366' }}>الوزن طن</th>
                                                                                                                    </tr>
                                                                                                                      </thead>
                                                                                                                        <tbody>
                                                                                                                            {allSteel.filter((item: any) => item.bars > 0).map((item: any, idx: number) => (
                                                                                                                                  <tr key={idx} style={{ background: idx % 2 === 0 ? 'white' : '#f8fafc' }}>
                                                                                                                                          <td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{item.label}</td>
                                                                                                                                                  <td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{item.diameter} مم</td>
                                                                                                                                                          <td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{item.bars}</td>
                                                                                                                                                                  <td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{fmtNum(item.ton)}</td>
                                                                                                                                                                        </tr>
                                                                                                                                                                            ))}
                                         {(() => {
                                             const summaryByDia: Record<number, number> = {};
                                               allSteel.forEach((item: any) => { summaryByDia[item.diameter] = (summaryByDia[item.diameter] || 0) + item.bars; });
                                                 return Object.entries(summaryByDia).sort(([a], [b]) => +a - +b).map(([dia, bars]) => (
                                                     <tr key={`sum-${dia}`} style={{ background: '#e8f0fe', fontWeight: 700 }}>
                                                           <td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>إجمالي</td>
                                                                 <td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{dia} مم</td>
                                                                       <td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{bars}</td>
                                                                             <td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{fmtNum(toTons(bars, Number(dia) as Dia))}</td>
                                                                                 </tr>
                                                                                   ));
                                                                                   })()}
                                                                                                                                                                              <tr style={{ background: '#003366', color: '#FFD700', fontWeight: 700 }}>
                                                                                                                                                                                      <td style={{ padding: '8px 5px', border: '1px solid #003366', textAlign: 'center' }}>الإجمالي الكلي</td>
                                                                                                                                                                                            <td style={{ padding: '8px 5px', border: '1px solid #003366', textAlign: 'center' }}>-</td>
                                                                                                                                                                                                  <td style={{ padding: '8px 5px', border: '1px solid #003366', textAlign: 'center' }}>-</td>
                                                                                                                                                                                                        <td style={{ padding: '8px 5px', border: '1px solid #003366', textAlign: 'center' }}>{fmtNum(totalSteelTon)}</td>
                                                                                                                                                                                                            </tr>
                                                                                                                                                                                                              </tbody>
                                                                                                                                                                                                              </table>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="no-print" style={{ display:'flex', gap:'6px', padding:'12px 15px', background:'white', borderTop:'1px solid #eee', marginTop:'auto' }}>
<button
  onClick={() => window.print()}
    style={{
        flex:1,
            padding:'10px',
                border:'none',
                    borderRadius:'10px',
                        background:'#28a745',
                            color:'white',
                                fontWeight:700,
                                    fontSize:'0.8rem',
                                        cursor:'pointer',
                                            fontFamily:'Cairo, sans-serif'
                                              }}
                                              >
                                                🖨️ طباعة التقرير
                                                </button>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default Middat;