import React, { useState, useEffect } from 'react';
import { n, fmtNum, goNext } from '../utils/constants';
import { projectStore, saveStore } from '../utils/projectStore';

const SectionTitle = ({ children }: { children: React.ReactNode }) => (
  <div style={{
      position: 'relative',
          padding: '8px 12px',
              marginBottom: '12px',
                  marginTop: '8px',
                      background: 'linear-gradient(to left, transparent, #e8f0fe 30%)',
                          borderRight: '4px solid #2563eb',
                              borderRadius: '0 8px 8px 0',
                                  boxShadow: '0 0 8px rgba(37,99,235,0.1)',
                                    }}>
                                        <span style={{ fontSize: '0.8rem', fontWeight: 800, color: '#003366' }}>{children}</span>
                                          </div>
                                          );

                                          const Num = ({ id, go, label, value, set, unit }: any) => (
                                            <div style={{ background: '#fdfdfd', border: '1px solid #ddd', borderRadius: '8px', padding: '8px 5px', textAlign: 'center' }}>
                                                <label style={{ fontSize: '0.6rem', color: '#003366', display: 'block', marginBottom: '2px', fontWeight: 700 }}>{label}</label>
                                                    <input
                                                          id={id} type="text" inputMode="decimal" autoComplete="off"
                                                                enterKeyHint={go ? 'next' : 'done'}
                                                                      style={{ width: '100%', border: 'none', textAlign: 'center', fontSize: '0.85rem', padding: '2px 0', outline: 'none', background: 'transparent', fontWeight: 700, fontFamily: 'Cairo, sans-serif' }}
                                                                            value={value} onChange={e => set(e.target.value)}
                                                                                  onFocus={e => e.target.select()}
                                                                                        onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); goNext(go); } }}
                                                                                            />
                                                                                                {unit && <span style={{ fontSize: '0.55rem', color: '#888', display: 'block', marginTop: '2px' }}>{unit}</span>}
                                                                                                  </div>
                                                                                                  );

                                                                                                  const Preliminary: React.FC = () => {
                                                                                                    // استرجاع المدخلات من localStorage إن وجدت
                                                                                                      const savedInputs = JSON.parse(localStorage.getItem('preliminary_inputs') || '{}');
                                                                                                        const [length, setLength] = useState(savedInputs.length || '20');
                                                                                                          const [width, setWidth] = useState(savedInputs.width || '15');
                                                                                                            const [excDepth, setExcDepth] = useState(savedInputs.excDepth || '1.5');
                                                                                                              const [backDepth, setBackDepth] = useState(savedInputs.backDepth || '0.5');
                                                                                                                const [chairHeight, setChairHeight] = useState(savedInputs.chairHeight || '0.3');

                                                                                                                  const l = n(length);
                                                                                                                    const w = n(width);
                                                                                                                      const area = l * w;
                                                                                                                        const excVolume = area * n(excDepth);
                                                                                                                          const backVolume = area * n(backDepth);
                                                                                                                            const chairArea = (2 * l + 2 * w) * n(chairHeight);

                                                                                                                              // حفظ المدخلات تلقائياً في localStorage عند تغيرها
                                                                                                                                useEffect(() => {
                                                                                                                                    const inputs = { length, width, excDepth, backDepth, chairHeight };
                                                                                                                                        localStorage.setItem('preliminary_inputs', JSON.stringify(inputs));
                                                                                                                                          }, [length, width, excDepth, backDepth, chairHeight]);

                                                                                                                                            // حفظ النتائج للملخص
                                                                                                                                              useEffect(() => {
                                                                                                                                                  const results = {
                                                                                                                                                        area: area,
                                                                                                                                                              excavation: excVolume,
                                                                                                                                                                    backfill: backVolume,
                                                                                                                                                                          stoneArea: chairArea
                                                                                                                                                                              };
                                                                                                                                                                                  localStorage.setItem('preliminary_results', JSON.stringify(results));
                                                                                                                                                                                    }, [area, excVolume, backVolume, chairArea]);

                                                                                                                                                                                      const calculate = () => {
                                                                                                                                                                                          projectStore.preliminary = { area, excVolume, backVolume, chairArea };
                                                                                                                                                                                              saveStore();
                                                                                                                                                                                                };

                                                                                                                                                                                                  const reset = () => {
                                                                                                                                                                                                      setLength('');
                                                                                                                                                                                                          setWidth('');
                                                                                                                                                                                                              setExcDepth('');
                                                                                                                                                                                                                  setBackDepth('');
                                                                                                                                                                                                                      setChairHeight('');
                                                                                                                                                                                                                        };

                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                              <>
                                                                                                                                                                                                                                    <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                                                                                                                                                                                                                                            {/* الأبعاد */}
                                                                                                                                                                                                                                                    <div className="model-card" style={{ border: '1px solid #ddd', borderRadius: '12px', overflow: 'hidden', background: 'white' }}>
                                                                                                                                                                                                                                                              <div className="model-body" style={{ padding: '10px 12px' }}>
                                                                                                                                                                                                                                                                          <SectionTitle>الأبعاد</SectionTitle>
                                                                                                                                                                                                                                                                                      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px', marginBottom: '12px' }}>
                                                                                                                                                                                                                                                                                                    <Num id="prelim-length" go="prelim-width" label="طول المبنى" value={length} set={setLength} unit="م" />
                                                                                                                                                                                                                                                                                                                  <Num id="prelim-width" go="prelim-exc" label="عرض المبنى" value={width} set={setWidth} unit="م" />
                                                                                                                                                                                                                                                                                                                                <Num id="prelim-exc" go="prelim-back" label="عمق الحفر" value={excDepth} set={setExcDepth} unit="م" />
                                                                                                                                                                                                                                                                                                                                              <Num id="prelim-back" go="prelim-chair" label="عمق الدفان" value={backDepth} set={setBackDepth} unit="م" />
                                                                                                                                                                                                                                                                                                                                                            <Num id="prelim-chair" label="ارتفاع الكرسي" value={chairHeight} set={setChairHeight} unit="م" />
                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                    <div className="no-print" style={{ display: 'flex', gap: '8px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={reset} style={{ flex: 1, padding: '10px', border: 'none', borderRadius: '10px', background: '#dc3545', color: 'white', fontWeight: 700, fontSize: '0.8rem', cursor: 'pointer', fontFamily: 'Cairo, sans-serif' }}>تفريغ المدخلات</button>
                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={calculate} style={{ flex: 1, padding: '10px', border: 'none', borderRadius: '10px', background: '#00509e', color: 'white', fontWeight: 700, fontSize: '0.8rem', cursor: 'pointer', fontFamily: 'Cairo, sans-serif' }}>حساب الكميات</button>
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* النتائج */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ pageBreakBefore: 'always' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <SectionTitle>النتائج</SectionTitle>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="results-grid" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="result-tile" style={{ border: '1px solid #28a745', borderRadius: '10px', padding: '10px 8px', textAlign: 'center', background: '#fafffe' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span style={{ fontSize: '0.55rem', color: '#555', fontWeight: 700 }}>مساحة المبنى</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <strong style={{ fontSize: '1rem', fontWeight: 700, color: '#28a745', display: 'block' }}>{fmtNum(area)} م²</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="result-tile" style={{ border: '1px solid #28a745', borderRadius: '10px', padding: '10px 8px', textAlign: 'center', background: '#fafffe' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span style={{ fontSize: '0.55rem', color: '#555', fontWeight: 700 }}>حجم الحفر</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <strong style={{ fontSize: '1rem', fontWeight: 700, color: '#28a745', display: 'block' }}>{fmtNum(excVolume)} م³</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="result-tile" style={{ border: '1px solid #28a745', borderRadius: '10px', padding: '10px 8px', textAlign: 'center', background: '#fafffe' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span style={{ fontSize: '0.55rem', color: '#555', fontWeight: 700 }}>كمية الدفان</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <strong style={{ fontSize: '1rem', fontWeight: 700, color: '#28a745', display: 'block' }}>{fmtNum(backVolume)} م³</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="result-tile" style={{ border: '1px solid #28a745', borderRadius: '10px', padding: '10px 8px', textAlign: 'center', background: '#fafffe' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span style={{ fontSize: '0.55rem', color: '#555', fontWeight: 700 }}>الكرسي الحجري</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <strong style={{ fontSize: '1rem', fontWeight: 700, color: '#28a745', display: 'block' }}>{fmtNum(chairArea)} م²</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* أزرار أسفل الصفحة */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="no-print" style={{ display: 'flex', gap: '6px', padding: '12px 15px', background: 'white', borderTop: '1px solid #eee', marginTop: 'auto' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button style={{ flex: 1, padding: '10px', border: 'none', borderRadius: '10px', background: '#28a745', color: 'white', fontWeight: 700, fontSize: '0.8rem', cursor: 'pointer', fontFamily: 'Cairo, sans-serif' }} onClick={() => window.print()}>🖨️ طباعة PDF</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default Preliminary;