import React, { useState, useEffect } from 'react';
import { n, fmtNum, goNext } from '../utils/constants';

const G = (k: string) => { try { const s = localStorage.getItem(k); return s ? JSON.parse(s) : null; } catch (e) { return null; } };

const STORAGE_KEY = 'quickcalc_inputs';

const SectionTitle = ({ children }: { children: React.ReactNode }) => (
  <div style={{ position: 'relative', padding: '8px 12px', marginBottom: '12px', marginTop: '8px', background: 'linear-gradient(to left, transparent, #e8f0fe 30%)', borderRight: '4px solid #2563eb', borderRadius: '0 8px 8px 0', boxShadow: '0 0 8px rgba(37,99,235,0.1)' }}>
      <span style={{ fontSize: '0.8rem', fontWeight: 800, color: '#003366' }}>{children}</span>
        </div>
        );

        const Num = ({ id, go, label, value, set, unit }: any) => (
          <div style={{ background: '#fdfdfd', border: '1px solid #ddd', borderRadius: '8px', padding: '8px 5px', textAlign: 'center' }}>
              <label style={{ fontSize: '0.6rem', color: '#003366', display: 'block', marginBottom: '2px', fontWeight: 700 }}>{label}</label>
                  <input
                        id={id} type="text" inputMode="decimal" autoComplete="off"
                              enterKeyHint={go ? 'next' : 'done'}
                                    style={{ width: '100%', border: 'none', textAlign: 'center', fontSize: '0.85rem', padding: '2px 0', outline: 'none', background: 'transparent', fontWeight: 700, fontFamily: 'Cairo, sans-serif' }}
                                          value={value} onChange={e => set(e.target.value)}
                                                onFocus={e => e.target.select()}
                                                      onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); goNext(go); } }}
                                                          />
                                                              {unit && <span style={{ fontSize: '0.55rem', color: '#888', display: 'block', marginTop: '2px' }}>{unit}</span>}
                                                                </div>
                                                                );

                                                                const QuickCalc: React.FC = () => {
                                                                  const saved = G(STORAGE_KEY) || {};
                                                                    const [length, setLength] = useState(saved.length || '15');
                                                                      const [width, setWidth] = useState(saved.width || '12');
                                                                        const [floors, setFloors] = useState(saved.floors || '2');

                                                                          useEffect(() => {
                                                                              localStorage.setItem(STORAGE_KEY, JSON.stringify({ length, width, floors }));
                                                                                }, [length, width, floors]);

                                                                                  const L = n(length), W = n(width), FL = n(floors);
                                                                                    const area = L * W;
                                                                                      const perimeter = 2 * (L + W);
const stoneArea = perimeter * 1.5;
                                                                                        const calculate = () => {};
                                                                                          const reset = () => { setLength(''); setWidth(''); setFloors(''); };// القواعد
                                                                                          const totalLoad = area * 1.5 * FL;
                                                                                          const footingArea = totalLoad / 20;
                                                                                          const footingConcrete = footingArea * 0.5;
                                                                                          const levelingConcrete = footingArea * 0.1;
                                                                                          const footingSteel = footingConcrete * 0.090;

                                                                                          // الأعمدة
                                                                                          const columnCount = Math.ceil(area / 9);
                                                                                          const colW = FL <= 2 ? 0.25 : FL <= 4 ? 0.30 : 0.35;
                                                                                          const colL = FL <= 2 ? 0.60 : FL <= 4 ? 0.70 : 0.80;
                                                                                          const colHeight = 3 * FL;
                                                                                          const columnConcrete = columnCount * colW * colL * colHeight;
                                                                                          const columnSteel = columnConcrete * 0.150;

                                                                                          // الرقاب
                                                                                          const neckCount = columnCount;
                                                                                          const neckConcrete = neckCount * colW * colL * 1.5;
                                                                                          const neckSteel = neckConcrete * 0.150;

                                                                                          // الميدات
                                                                                          const middLength = perimeter * 2;
                                                                                          const middConcrete = middLength * 0.25 * 0.40;
                                                                                          const middSteel = middConcrete * 0.150;

                                                                                          // السقف
                                                                                          const slabSteel = area / 30 * FL;
                                                                                          const slabConcrete = area * 0.22 * FL;

                                                                                          // الإجماليات
                                                                                          const totalConcrete = footingConcrete + levelingConcrete + columnConcrete + neckConcrete + middConcrete + slabConcrete;
                                                                                          const totalSteel = footingSteel + columnSteel + neckSteel + middSteel + slabSteel;

                                                                                          // التشطيبات
                                                                                          const finArea = area * FL;
                                                                                          const finPerimeter = perimeter * FL;
                                                                                          const finWallArea = finPerimeter * 3;
                                                                                          const finWindows = Math.ceil(area * 0.10);
                                                                                          const finDoors = Math.ceil(area * 0.05);
                                                                                          const finInnerWall = finWallArea * 0.6;
                                                                                          const finBlocks = Math.ceil((finWallArea + finInnerWall) / 0.08);
                                                                                          const finBlockCement = Math.ceil((finBlocks / 1000) * 20);
                                                                                          const finBlockSand = finBlockCement * 0.1;
                                                                                          const finPlasterArea = finWallArea + finInnerWall * 2 + finArea;
                                                                                          const finPlasterCement = Math.ceil((finPlasterArea / 100) * 20);
                                                                                          const finPlasterSand = finPlasterCement * 0.1;
                                                                                          const finPaintArea = finPlasterArea;
                                                                                          const finPutty = finPaintArea * 0.5;
                                                                                          const finPrimer = finPaintArea / 10;
                                                                                          const finPaint = finPaintArea / 20;
                                                                                          const finTileFloor = finArea * 0.85;
                                                                                          const finTileBath = 2 * FL * 4 * 1.5 * 3;
                                                                                          const finTileKitchen = 1 * FL * 4 * 3 * 3;
                                                                                          const finTotalDoors = finDoors * FL;
                                                                                          const finTotalWindows = finWindows * FL;return (
                                                                                              <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>

                                                                                                  {/* المدخلات */}
                                                                                                      <div className="model-card" style={{ border: '1px solid #ddd', borderRadius: '12px', overflow: 'hidden', background: 'white' }}>
                                                                                                            <div className="model-body" style={{ padding: '10px 12px' }}>
                                                                                                                    <SectionTitle>أبعاد المبنى</SectionTitle>
                                                                                                                            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '8px', marginBottom: '12px' }}>
                                                                                                                                      <Num id="qc-length" go="qc-width" label="الطول" value={length} set={setLength} unit="م" />
                                                                                                                                                <Num id="qc-width" go="qc-floors" label="العرض" value={width} set={setWidth} unit="م" />
                                                                                                                                                          <Num id="qc-floors" label="عدد الأدوار" value={floors} set={setFloors} unit="دور" />
                                                                                                                                                                  </div>

                                                                                                                                                                          <div className="no-print" style={{ display: 'flex', gap: '8px' }}>
                                                                                                                                                                                    <button onClick={reset} style={{ flex: 1, padding: '10px', border: 'none', borderRadius: '10px', background: '#dc3545', color: 'white', fontWeight: 700, fontSize: '0.8rem', cursor: 'pointer', fontFamily: 'Cairo, sans-serif' }}>تفريغ</button>
                                                                                                                                                                                              <button onClick={calculate} style={{ flex: 1, padding: '10px', border: 'none', borderRadius: '10px', background: '#00509e', color: 'white', fontWeight: 700, fontSize: '0.8rem', cursor: 'pointer', fontFamily: 'Cairo, sans-serif' }}>🧮 احسب بسرعة</button>
                                                                                                                                                                                                      </div>
                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                    {/* النتائج */}
                                                                                                                                                                                                                        <div style={{ pageBreakBefore: 'always' }}>
                                                                                                                                                                                                                              <SectionTitle>📊 ملخص تقريبي ({FL} أدوار)</SectionTitle>

                                                                                                                                                                                                                                    <div className="model-card" style={{ border: '1px solid #ddd', borderRadius: '12px', overflow: 'hidden', background: 'white', marginBottom: '8px' }}>
                                                                                                                                                                                                                                            <div className="model-body" style={{ padding: '10px 12px' }}>
                                                                                                                                                                                                                                                      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.7rem' }}>
                                                                                                                                                                                                                                                                  <thead>
                                                                                                                                                                                                                                                                                <tr style={{ background: '#003366', color: 'white' }}>
                                                                                                                                                                                                                                                                                                <th style={{ padding: '8px 5px', border: '1px solid #003366' }}>البند</th>
                                                                                                                                                                                                                                                                                                                <th style={{ padding: '8px 5px', border: '1px solid #003366' }}>خرسانة (م³)</th>
                                                                                                                                                                                                                                                                                                                                <th style={{ padding: '8px 5px', border: '1px solid #003366' }}>حديد (طن)</th>
                                                                                                                                                                                                                                                                                                                                              </tr>
                                                                                                                                                                                                                                                                                                                                                          </thead>
                                                                                                                                                                                                                                                                                                                                                                      <tbody>
                                                                                                                                                                                                                                                                                                                                                                                    <tr><td style={{ padding: '6px 5px', border: '1px solid #ccc', fontWeight: 700 }}>🧱 القواعد</td><td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{fmtNum(footingConcrete + levelingConcrete)}</td><td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{fmtNum(footingSteel)}</td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                  <tr><td style={{ padding: '6px 5px', border: '1px solid #ccc', fontWeight: 700 }}>🏛️ الأعمدة</td><td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{fmtNum(columnConcrete)}</td><td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{fmtNum(columnSteel)}</td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                <tr><td style={{ padding: '6px 5px', border: '1px solid #ccc', fontWeight: 700 }}>📏 الرقاب</td><td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{fmtNum(neckConcrete)}</td><td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{fmtNum(neckSteel)}</td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                              <tr><td style={{ padding: '6px 5px', border: '1px solid #ccc', fontWeight: 700 }}>〰️ الميدات</td><td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{fmtNum(middConcrete)}</td><td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{fmtNum(middSteel)}</td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <tr><td style={{ padding: '6px 5px', border: '1px solid #ccc', fontWeight: 700 }}>🟫 السقف</td><td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{fmtNum(slabConcrete)}</td><td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{fmtNum(slabSteel)}</td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <tr style={{ background: '#003366', color: '#FFD700', fontWeight: 700 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <td style={{ padding: '8px 5px', border: '1px solid #003366', textAlign: 'center' }}>الإجمالي</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <td style={{ padding: '8px 5px', border: '1px solid #003366', textAlign: 'center' }}>{fmtNum(totalConcrete)}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <td style={{ padding: '8px 5px', border: '1px solid #003366', textAlign: 'center' }}>{fmtNum(totalSteel)}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>        <div className="model-card" style={{ border: '1px solid #ddd', borderRadius: '12px', overflow: 'hidden', background: 'white', marginBottom: '8px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="model-body" style={{ padding: '10px 12px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.7rem' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tr style={{ background: '#003366', color: 'white' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <th style={{ padding: '8px 5px', border: '1px solid #003366' }}>بند التشطيبات</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <th style={{ padding: '8px 5px', border: '1px solid #003366' }}>الكمية</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tr><td style={{ padding: '6px 5px', border: '1px solid #ccc', fontWeight: 700 }}>🧱 عدد البلك</td><td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{finBlocks} بلوكة</td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tr><td style={{ padding: '6px 5px', border: '1px solid #ccc', fontWeight: 700 }}>🏗️ تلييس</td><td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{fmtNum(finPlasterArea)} م²</td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tr><td style={{ padding: '6px 5px', border: '1px solid #ccc', fontWeight: 700 }}>🎨 طلاء</td><td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{fmtNum(finPaintArea)} م²</td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tr><td style={{ padding: '6px 5px', border: '1px solid #ccc', fontWeight: 700 }}>🟫 بلاط الأرضيات</td><td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{fmtNum(finTileFloor)} م²</td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tr><td style={{ padding: '6px 5px', border: '1px solid #ccc', fontWeight: 700 }}>🟫 بلاط الحمامات</td><td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{fmtNum(finTileBath)} م²</td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tr><td style={{ padding: '6px 5px', border: '1px solid #ccc', fontWeight: 700 }}>🟫 بلاط المطابخ</td><td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{fmtNum(finTileKitchen)} م²</td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tr><td style={{ padding: '6px 5px', border: '1px solid #ccc', fontWeight: 700 }}>🚪 الأبواب</td><td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{finTotalDoors} باب</td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tr><td style={{ padding: '6px 5px', border: '1px solid #ccc', fontWeight: 700 }}>🪟 النوافذ</td><td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{finTotalWindows} نافذة</td></tr>
                                          <tr><td style={{ padding: '6px 5px', border: '1px solid #ccc', fontWeight: 700 }}>🏗️ أسمنت البناء</td><td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{finBlockCement} كيس</td></tr>
                                          <tr><td style={{ padding: '6px 5px', border: '1px solid #ccc', fontWeight: 700 }}>🏗️ رمل البناء</td><td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{fmtNum(finBlockSand)} م³</td></tr>
                                          <tr><td style={{ padding: '6px 5px', border: '1px solid #ccc', fontWeight: 700 }}>🏗️ أسمنت التلييس</td><td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{finPlasterCement} كيس</td></tr>
                                          <tr><td style={{ padding: '6px 5px', border: '1px solid #ccc', fontWeight: 700 }}>🏗️ رمل التلييس</td><td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{fmtNum(finPlasterSand)} م³</td></tr>
                                          <tr><td style={{ padding: '6px 5px', border: '1px solid #ccc', fontWeight: 700 }}>🎨 المعجون</td><td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{fmtNum(finPutty)} كجم</td></tr>
                                          <tr><td style={{ padding: '6px 5px', border: '1px solid #ccc', fontWeight: 700 }}>🎨 البرايمر</td><td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{fmtNum(finPrimer)} لتر</td></tr>
                                          <tr><td style={{ padding: '6px 5px', border: '1px solid #ccc', fontWeight: 700 }}>🎨 الطلاء</td><td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{fmtNum(finPaint)} جالون</td></tr>
                                           <tr><td style={{ padding: '6px 5px', border: '1px solid #ccc', fontWeight: 700 }}>⛏️ الكرسي الحجري</td><td style={{ padding: '6px 5px', border: '1px solid #ccc', textAlign: 'center' }}>{fmtNum(stoneArea)} م²</td></tr>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* أزرار */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="no-print" style={{ display: 'flex', gap: '8px', padding: '12px 0' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={() => window.print()} style={{ flex: 1, padding: '12px', border: 'none', borderRadius: '10px', background: '#00509e', color: 'white', fontWeight: 700, fontSize: '0.85rem', cursor: 'pointer', fontFamily: 'Cairo, sans-serif' }}>🖨️ طباعة PDF</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default QuickCalc;
                                                                                          