import { BARS_PER_TON } from '../types';

export const barsToTons = (bars: number, diameter: number): number => {
  return bars / (BARS_PER_TON[diameter] || 100);
  };

  export const lengthToBars = (length: number): number => {
    return Math.ceil(length / 12);
    };

    export const roundUp = (num: number, decimals: number = 2): number => {
      const factor = Math.pow(10, decimals);
        return Math.ceil(num * factor) / factor;
        };

        export const roundDown = (num: number, decimals: number = 0): number => {
          const factor = Math.pow(10, decimals);
            return Math.floor(num * factor) / factor;
            };

            export const calculateFoundation = (f: any) => {
              const concrete = f.count * f.length * f.width * f.height;
                const levelingConcrete = f.count * (f.length - 0.1) * (f.width - 0.1) * 0.1;
                  const longSteelOne = (f.length - 0.1 + 0.3) * (f.width - 0.1) * f.longBarsPerMeter;
                    const transSteelOne = (f.width - 0.1 + 0.3) * (f.length - 0.1) * f.transBarsPerMeter;
                      const totalMainLength = (longSteelOne + transSteelOne) * f.count;
                        const mainBars = lengthToBars(totalMainLength);
                          const stirrupOne = (6 * f.length + 4 * f.height) + (6 * f.width + 4 * f.height);
                            const totalStirrupLength = stirrupOne * f.count;
                              const stirrupBars = lengthToBars(totalStirrupLength);
                                const chairArea = (2 * f.buildingLength + 2 * f.buildingWidth) * f.stoneChairHeight;
                                  return {
                                      concrete,
                                          levelingConcrete,
                                              mainBars,
                                                  mainTons: barsToTons(mainBars, f.mainBarDiameter),
                                                      stirrupBars,
                                                          stirrupTons: barsToTons(stirrupBars, f.stirrupDiameter),
                                                              chairArea,
                                                                  steelByDiameter: {
                                                                        [f.mainBarDiameter]: mainBars,
                                                                              [f.stirrupDiameter]: stirrupBars,
                                                                                  },
                                                                                    };
                                                                                    };

                                                                                    export const calculateColumnStubs = (columns: any[]) => {
                                                                                      const result: Record<number, number> = {};
                                                                                        columns.forEach(c => {
                                                                                            const bars = c.count * c.mainBarCount;
                                                                                                const length = bars * 2;
                                                                                                    const barCount = lengthToBars(length);
                                                                                                        result[c.mainBarDiameter] = (result[c.mainBarDiameter] || 0) + barCount;
                                                                                                          });
                                                                                                            return result;
                                                                                                            };

                                                                                                            export const calculateNeck = (n: any, middaHeight: number = 0.4) => {
                                                                                                              const concrete = n.count * n.length * n.width * n.height;
                                                                                                                const verticalLength = n.height + n.baseThickness + middaHeight + 1.0;
                                                                                                                  const totalVertical = n.count * n.barCount * verticalLength;
                                                                                                                    const verticalBars = lengthToBars(totalVertical);
                                                                                                                      const stirrupCount = n.count * n.height * n.stirrupsPerMeter;
                                                                                                                        const stirrupLength = 2 * (n.length + n.width) + 0.2;
                                                                                                                          const totalStirrupLength = stirrupCount * stirrupLength;
                                                                                                                            const stirrupBars = lengthToBars(totalStirrupLength);
                                                                                                                              return {
                                                                                                                                  concrete,
                                                                                                                                      verticalBars,
                                                                                                                                          verticalTons: barsToTons(verticalBars, n.barDiameter),
                                                                                                                                              stirrupBars,
                                                                                                                                                  stirrupTons: barsToTons(stirrupBars, n.stirrupDiameter),
                                                                                                                                                      steelByDiameter: {
                                                                                                                                                            [n.barDiameter]: verticalBars,
                                                                                                                                                                  [n.stirrupDiameter]: stirrupBars,
                                                                                                                                                                      },
                                                                                                                                                                        };
                                                                                                                                                                        };

                                                                                                                                                                        export const calculateColumn = (c: any) => {
                                                                                                                                                                          const concrete = c.count * c.length * c.width * c.height;
                                                                                                                                                                            const verticalOneLength = c.height + 0.7 + 0.3;
                                                                                                                                                                              const totalVertical = c.count * c.mainBarCount * verticalOneLength;
                                                                                                                                                                                const verticalBars = lengthToBars(totalVertical);
                                                                                                                                                                                  const stirrupCount = c.count * c.height * c.stirrupsPerMeter;
                                                                                                                                                                                    const stirrupLength = 2 * (c.length + c.width) + 0.2;
                                                                                                                                                                                      const totalStirrup = stirrupCount * stirrupLength;
                                                                                                                                                                                        const stirrupBars = lengthToBars(totalStirrup);
                                                                                                                                                                                          return {
                                                                                                                                                                                              concrete,
                                                                                                                                                                                                  verticalBars,
                                                                                                                                                                                                      verticalTons: barsToTons(verticalBars, c.mainBarDiameter),
                                                                                                                                                                                                          stirrupBars,
                                                                                                                                                                                                              stirrupTons: barsToTons(stirrupBars, c.stirrupDiameter),
                                                                                                                                                                                                                  steelByDiameter: {
                                                                                                                                                                                                                        [c.mainBarDiameter]: verticalBars,
                                                                                                                                                                                                                              [c.stirrupDiameter]: stirrupBars,
                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                    export const calculateMidda = (m: any) => {
                                                                                                                                                                                                                                      const totalLength = m.buildingLength * m.lengthAxes + m.buildingWidth * m.widthAxes;
                                                                                                                                                                                                                                        const topBars = Math.ceil((m.topBarsCount * totalLength * 1.1) / 12);
                                                                                                                                                                                                                                          const bottomBars = Math.ceil((m.bottomBarsCount * totalLength * 1.1) / 12);
                                                                                                                                                                                                                                            const stirrupBars = Math.ceil((totalLength * 5 * 1.3) / 12);
                                                                                                                                                                                                                                              const concrete = roundUp(totalLength * 0.2 * m.middaHeight, 2);
                                                                                                                                                                                                                                                const steelByDiameter: Record<number, number> = {};
                                                                                                                                                                                                                                                  steelByDiameter[m.topBarDiameter] = (steelByDiameter[m.topBarDiameter] || 0) + topBars;
                                                                                                                                                                                                                                                    steelByDiameter[m.bottomBarDiameter] = (steelByDiameter[m.bottomBarDiameter] || 0) + bottomBars;
                                                                                                                                                                                                                                                      steelByDiameter[m.stirrupDiameter] = (steelByDiameter[m.stirrupDiameter] || 0) + stirrupBars;
                                                                                                                                                                                                                                                        return { concrete, topBars, topTons: barsToTons(topBars, m.topBarDiameter), bottomBars, bottomTons: barsToTons(bottomBars, m.bottomBarDiameter), stirrupBars, stirrupTons: barsToTons(stirrupBars, m.stirrupDiameter), middaHeight: m.middaHeight, steelByDiameter };
                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                        export const calculateSlab = (s: any) => {
                                                                                                                                                                                                                                                          const area = s.length * s.width;
                                                                                                                                                                                                                                                            const ribsCount = roundDown((s.width - (s.lengthBeams * s.lengthBeamWidth)) * 2, 0);
                                                                                                                                                                                                                                                              const totalRibLength = ribsCount * s.length;
                                                                                                                                                                                                                                                                const blockCount = Math.ceil(((s.length - (s.widthBeams * s.widthBeamWidth)) / 0.2) * ribsCount);
                                                                                                                                                                                                                                                                  const blockVolume = blockCount * 0.016;
                                                                                                                                                                                                                                                                    const grossSlabVolume = area * s.slabThickness;
                                                                                                                                                                                                                                                                      const concrete = Math.ceil(grossSlabVolume - blockVolume);
                                                                                                                                                                                                                                                                        const steelByDiameter: Record<number, number> = {};
                                                                                                                                                                                                                                                                          const addSteel = (diameter: number, bars: number) => { if (bars > 0) steelByDiameter[diameter] = (steelByDiameter[diameter] || 0) + bars; };
                                                                                                                                                                                                                                                                            addSteel(s.lengthTopDiameter, Math.ceil((s.lengthTopBars * s.length * s.lengthBeams * 1.1) / 12));
                                                                                                                                                                                                                                                                              addSteel(s.lengthBottomDiameter, Math.ceil((s.lengthBottomBars * s.length * s.lengthBeams * 1.1) / 12));
                                                                                                                                                                                                                                                                                addSteel(s.widthTopDiameter, Math.ceil((s.widthTopBars * s.width * s.widthBeams * 1.1) / 12));
                                                                                                                                                                                                                                                                                  addSteel(s.widthBottomDiameter, Math.ceil((s.widthBottomBars * s.width * s.widthBeams * 1.1) / 12));
                                                                                                                                                                                                                                                                                    addSteel(s.topBarDiameter, Math.ceil((ribsCount * s.topBarsCount * s.length * 1.1) / 12));
                                                                                                                                                                                                                                                                                      addSteel(s.bottomBarDiameter, Math.ceil((ribsCount * s.bottomBarsCount * s.length * 1.1) / 12));
                                                                                                                                                                                                                                                                                        addSteel(8, Math.ceil((s.length * s.lengthBeams * 6 * 1.8) / 12) + Math.ceil((s.width * s.widthBeams * 6 * 1.8) / 12) + Math.ceil((totalRibLength * 5 * 0.6) / 12) + Math.ceil(((s.length * 5 * s.width) / 12) * 2 - 7));
                                                                                                                                                                                                                                                                                          let totalSteelTon = 0;
                                                                                                                                                                                                                                                                                            Object.entries(steelByDiameter).forEach(([d, b]) => { totalSteelTon += barsToTons(b, Number(d)); });
                                                                                                                                                                                                                                                                                              return { ribsCount, totalRibLength, area, grossSlabVolume, blockCount, blockVolume, concrete, steelByDiameter, totalSteelTon };
                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                              export const calculateTank = (t: any) => {
                                                                                                                                                                                                                                                                                                const capacity = t.length * t.width * t.height;
                                                                                                                                                                                                                                                                                                  const floorConcrete = t.length * t.width * t.floorThickness;
                                                                                                                                                                                                                                                                                                    const roofConcrete = t.length * t.width * t.roofThickness;
                                                                                                                                                                                                                                                                                                      const wallArea = (2 * t.length + 2 * t.width) * t.height;
                                                                                                                                                                                                                                                                                                        const wallConcrete = wallArea * t.wallThickness;
                                                                                                                                                                                                                                                                                                          const totalConcrete = floorConcrete + roofConcrete + wallConcrete;
                                                                                                                                                                                                                                                                                                            const steelByDiameter: Record<number, number> = {};
                                                                                                                                                                                                                                                                                                              const addReinf = (rein: any, area: number) => {
                                                                                                                                                                                                                                                                                                                  if (!rein || rein.layers <= 0) return;
                                                                                                                                                                                                                                                                                                                      const longBars = Math.ceil((area * rein.longBars / 0.2) * rein.layers / 12);
                                                                                                                                                                                                                                                                                                                          const transBars = Math.ceil((area * rein.transBars / 0.2) * rein.layers / 12);
                                                                                                                                                                                                                                                                                                                              steelByDiameter[rein.longDiameter] = (steelByDiameter[rein.longDiameter] || 0) + longBars;
                                                                                                                                                                                                                                                                                                                                  steelByDiameter[rein.transDiameter] = (steelByDiameter[rein.transDiameter] || 0) + transBars;
                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                      addReinf(t.wallReinf, wallArea);
                                                                                                                                                                                                                                                                                                                                        addReinf(t.floorReinf, t.length * t.width);
                                                                                                                                                                                                                                                                                                                                          addReinf(t.roofReinf, t.length * t.width);
                                                                                                                                                                                                                                                                                                                                            const totalBars = Object.values(steelByDiameter).reduce((s, v) => s + v, 0);
                                                                                                                                                                                                                                                                                                                                              const totalTons = Object.entries(steelByDiameter).reduce((s, [d, v]) => s + barsToTons(v, Number(d)), 0);
                                                                                                                                                                                                                                                                                                                                                return { capacity, floorConcrete, roofConcrete, wallConcrete, totalConcrete, steelByDiameter, totalBars, totalTons };
                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                export const calculatePreliminary = (p: any) => {
                                                                                                                                                                                                                                                                                                                                                  const area = p.length * p.width;
                                                                                                                                                                                                                                                                                                                                                    const excavationVolume = area * p.excavationDepth;
                                                                                                                                                                                                                                                                                                                                                      const backfillVolume = area * p.backfillDepth;
                                                                                                                                                                                                                                                                                                                                                        return { area, excavationVolume, backfillVolume, levelingArea: area };
                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                        export const calculateStructural = (s: any) => {
                                                                                                                                                                                                                                                                                                                                                          const A = s.buildingArea;
                                                                                                                                                                                                                                                                                                                                                            const N = s.floors;
                                                                                                                                                                                                                                                                                                                                                              const SBC = s.soilCapacity;
                                                                                                                                                                                                                                                                                                                                                                const floorWeight = A * 17;
                                                                                                                                                                                                                                                                                                                                                                  const buildingWeight = A * 17 * N;
                                                                                                                                                                                                                                                                                                                                                                    const requiredFootingArea = SBC > 0 ? buildingWeight / SBC : 0;
                                                                                                                                                                                                                                                                                                                                                                      const footingRatio = A > 0 ? (requiredFootingArea / A) * 100 : 0;
                                                                                                                                                                                                                                                                                                                                                                        const tributaryArea = ((s.length1 / 2) + (s.length2 / 2)) * ((s.width1 / 2) + (s.width2 / 2));
                                                                                                                                                                                                                                                                                                                                                                          const columnLoad = ((tributaryArea * 17) + 15) * N;
                                                                                                                                                                                                                                                                                                                                                                            const requiredColumnFooting = SBC > 0 ? columnLoad / SBC : 0;
                                                                                                                                                                                                                                                                                                                                                                              const footingSide = Math.sqrt(requiredColumnFooting);
                                                                                                                                                                                                                                                                                                                                                                                const Ag = s.columnLength * s.columnWidth;
                                                                                                                                                                                                                                                                                                                                                                                  const d_m = s.barDiameter / 1000;
                                                                                                                                                                                                                                                                                                                                                                                    const barArea = Math.PI * d_m * d_m / 4;
                                                                                                                                                                                                                                                                                                                                                                                      const As = s.barCount * barArea;
                                                                                                                                                                                                                                                                                                                                                                                        const Ac = Ag - As;
                                                                                                                                                                                                                                                                                                                                                                                          const fc_kN = s.fc * 1000;
                                                                                                                                                                                                                                                                                                                                                                                            const fy_kN = s.fy * 1000;
                                                                                                                                                                                                                                                                                                                                                                                              const Pn = 0.85 * fc_kN * Ac + fy_kN * As;
                                                                                                                                                                                                                                                                                                                                                                                                const phi = 0.65;
                                                                                                                                                                                                                                                                                                                                                                                                  const designCapacity = phi * Pn;
                                                                                                                                                                                                                                                                                                                                                                                                    const columnSafe = designCapacity >= columnLoad;
                                                                                                                                                                                                                                                                                                                                                                                                      const steelRatio = Ag > 0 ? (As / Ag) * 100 : 0;
                                                                                                                                                                                                                                                                                                                                                                                                        const requiredColumnArea = s.requiredLoad > 0 ? s.requiredLoad / 2500 : 0;
                                                                                                                                                                                                                                                                                                                                                                                                          const columnSide = Math.sqrt(requiredColumnArea);
                                                                                                                                                                                                                                                                                                                                                                                                            const allowableSoilLoad = s.actualFootingArea * SBC;
                                                                                                                                                                                                                                                                                                                                                                                                              const footingOK = allowableSoilLoad >= buildingWeight;
                                                                                                                                                                                                                                                                                                                                                                                                                const buildingWeightTon = buildingWeight / 10;
                                                                                                                                                                                                                                                                                                                                                                                                                  return { floorWeight, buildingWeight, buildingWeightTon, requiredFootingArea, footingRatio, tributaryArea, columnLoad, requiredColumnFooting, footingSide, Ag, As, Ac, Pn, designCapacity, columnSafe, steelRatio, requiredColumnArea, columnSide, allowableSoilLoad, footingOK };
                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                  // ========== دوال الحديد المساعدة ==========
                                                                                                                                                                                                                                                                                                                                                                                                                  export const steelDiameters = [8, 10, 12, 14, 16, 18, 20] as const;

                                                                                                                                                                                                                                                                                                                                                                                                                  export const emptySteel = (): Record<number, { bars: number; ton: number }> => {
                                                                                                                                                                                                                                                                                                                                                                                                                    const s: Record<number, { bars: number; ton: number }> = {};
                                                                                                                                                                                                                                                                                                                                                                                                                      steelDiameters.forEach(d => {
                                                                                                                                                                                                                                                                                                                                                                                                                          s[d] = { bars: 0, ton: 0 };
                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                              return s;
                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                              export const addSteelHelper = (
                                                                                                                                                                                                                                                                                                                                                                                                                                steel: Record<number, { bars: number; ton: number }>,
                                                                                                                                                                                                                                                                                                                                                                                                                                  diameter: number,
                                                                                                                                                                                                                                                                                                                                                                                                                                    bars: number
                                                                                                                                                                                                                                                                                                                                                                                                                                    ) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!steel[diameter]) steel[diameter] = { bars: 0, ton: 0 };
                                                                                                                                                                                                                                                                                                                                                                                                                                        steel[diameter].bars += bars;
                                                                                                                                                                                                                                                                                                                                                                                                                                          steel[diameter].ton = steel[diameter].bars / (BARS_PER_TON[diameter] || 100);
                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                          export const steelBars = (length: number): number => {
                                                                                                                                                                                                                                                                                                                                                                                                                                            return Math.ceil(length / 12);
                                                                                                                                                                                                                                                                                                                                                                                                                                            };